sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t friendlygreen .
  - docker run -d -p 127.0.0.1:80:4567 friendlygreen
  - docker ps -a
  
script:
 - ant;
 - ant test;
