sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t friendlygreen .
  - docker run -d -p 4000:80 friendlygreen
  - docker ps -a
  - docker run friendlygreen

script:
 - ant;
 - ant test;
